version: "3.4"

services:
  backend:
    image: heartbeat_backend:latest
    container_name: backend
    expose:
      - 4322
    restart: always
    deploy:
      replicas: 3
    volumes:
      - file_volume:/app/output
    networks:
      - default
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-default}
      - MOCK_SERVER_URL=${MOCK_SERVER_URL:-localhost:4323}
      - BACKEND_SECRET_KEY=fake
      - FIXED_SALT=fake
  frontend:
    image: heartbeat_frontend:latest
    container_name: frontend
    ports:
      - 4321:80
    depends_on:
      - backend
    restart: always
    networks:
      - default
  stub:
    image: heartbeat_stub:latest
    container_name: stub
    ports:
      - "${MOCK_SERVER_PORT:-4323}:4323"
    restart: always
    networks:
      - default
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  file_volume:
networks:
  default:
    driver: bridge
