spring:
  profiles:
    active: default

server:
  port: 4322
  servlet:
    context-path: /api/v1
logging:
  level:
    root: INFO

githubFeignClient:
  url: https://api.github.com

jira:
  url: https://demo.atlassian.net

buildKite:
  url: ${MOCK_SERVER_URL}
