server:
  port: 4322
  servlet:
    context-path: /api/v1
logging:
  level:
    root: INFO

githubFeignClient:
  url: ${MOCK_SERVER_URL:http://localhost:4323}

jira:
  url: ${MOCK_SERVER_URL:http://localhost:4323}

buildKite:
  url: ${MOCK_SERVER_URL:http://localhost:4323}

